package com.flagent.gradle.tasks

import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import com.fasterxml.jackson.module.kotlin.readValue
import com.flagent.gradle.FlagentExtension
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File
import java.net.URI
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse

/**
 * Generates FlagKeys.kt (object or enum) from Flagent API or flags file.
 * Register output dir in sourceSets so generated code is compiled.
 */
abstract class GenerateFlagKeysTask : DefaultTask() {

    @get:org.gradle.api.tasks.Internal
    abstract val extension: Property<FlagentExtension>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val ext = extension.get()
        val keys = when {
            ext.flagsFile.orNull?.asFile?.exists() == true -> loadFromFile(ext.flagsFile.get().asFile)
            else -> fetchFromApi(ext.baseUrl.get(), ext.apiKey.get())
        }
        if (keys.isEmpty()) {
            logger.warn("generateFlagKeys: no keys from API or file; skipping generation")
            return
        }
        val format = ext.flagKeysFormat.get().lowercase().let {
            if (it != "enum") "object" else "enum"
        }
        val pkg = ext.flagKeysPackage.get().trim().ifEmpty { "flagent.generated" }
        val content = if (format == "object") generateObject(pkg, keys) else generateEnum(pkg, keys)
        val outDir = outputDir.get().asFile
        outDir.mkdirs()
        val outFile = File(outDir, "FlagKeys.kt")
        outFile.writeText(content)
        logger.lifecycle("generateFlagKeys: wrote {} keys to {}", keys.size, outFile)
    }

    private fun loadFromFile(file: File): Set<String> {
        val content = file.readText()
        val mapper = when {
            file.extension.lowercase() in listOf("yaml", "yml") ->
                ObjectMapper(YAMLFactory()).findAndRegisterModules()
            else -> jacksonObjectMapper()
        }
        val tree = mapper.readTree(content)
        val flags = when {
            tree.isObject && tree.has("flags") -> tree.get("flags")
            tree.isArray -> tree
            else -> mapper.createArrayNode()
        }
        return (0 until flags.size()).mapNotNull { flags.get(it).get("key")?.asText()?.takeIf { k -> k.isNotBlank() } }.toSet()
    }

    private fun fetchFromApi(baseUrl: String, apiKey: String): Set<String> {
        val url = baseUrl.trimEnd('/').let {
            if (it.endsWith("/api/v1")) it else "$it/api/v1"
        } + "/flags?limit=1000"
        val client = HttpClient.newBuilder().build()
        val reqBuilder = HttpRequest.newBuilder(URI.create(url)).header("Accept", "application/json")
        if (apiKey.isNotBlank()) reqBuilder.header("X-API-Key", apiKey)
        val res = client.send(reqBuilder.build(), HttpResponse.BodyHandlers.ofString())
        if (res.statusCode() != 200) {
            logger.warn("generateFlagKeys: API returned {}, no keys loaded", res.statusCode())
            return emptySet()
        }
        @Suppress("UNCHECKED_CAST")
        val flags = jacksonObjectMapper().readValue<List<Map<String, Any>>>(res.body())
        return flags.mapNotNull { it["key"]?.toString() }.toSet()
    }

    /**
     * Convert flag key to valid Kotlin constant name (UPPER_SNAKE_CASE).
     * Leading digits get prefix; invalid chars replaced with underscore.
     */
    private fun keyToConstantName(key: String): String {
        if (key.isBlank()) return "UNKNOWN"
        val normalized = key.trim()
            .replace(Regex("[^a-zA-Z0-9_]"), "_")
            .replace(Regex("_+"), "_")
            .trim('_')
        if (normalized.isEmpty()) return "UNKNOWN"
        val upper = normalized.uppercase()
        return if (upper[0].isDigit()) "KEY_$upper" else upper
    }

    private fun generateObject(pkg: String, keys: Set<String>): String {
        val lines = keys.sorted().map { key ->
            val name = keyToConstantName(key)
            "    const val $name: String = \"$key\""
        }
        return """
            |// Generated by Flagent Gradle plugin — do not edit
            |package $pkg
            |
            |object FlagKeys {
            |${lines.joinToString("\n")}
            |}
            |
        """.trimMargin()
    }

    private fun generateEnum(pkg: String, keys: Set<String>): String {
        val entries = keys.sorted().map { key ->
            val name = keyToConstantName(key)
            "    $name(\"$key\")"
        }
        return """
            |// Generated by Flagent Gradle plugin — do not edit
            |package $pkg
            |
            |enum class FlagKey(val key: String) {
            |${entries.joinToString(",\n")}
            |}
            |
        """.trimMargin()
    }
}
