/*
Flagent API

Flagent is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". ## Authentication Flagent supports multiple authentication methods (configured via environment variables): - **JWT Authentication**: Bearer token authentication - **Basic Authentication**: Username/password authentication - **Header Authentication**: Custom header-based authentication - **Cookie Authentication**: Cookie-based authentication Some endpoints (like `/health`, `/evaluation`) may be whitelisted and don't require authentication. ## Error Responses All error responses follow the same format: ```json {   \"message\": \"Error description\" } ``` Common HTTP status codes: - `200`: Success - `400`: Bad Request - invalid input parameters - `404`: Not Found - resource doesn't exist - `429`: Too Many Requests - rate limit exceeded - `500`: Internal Server Error - server error ## Rate Limiting Rate limiting is configured via environment variables: - `FLAGENT_RATELIMITER_PERFLAG_PERSECOND_CONSOLE_LOGGING`: Maximum evaluations per flag per second (default: 100) When rate limit is exceeded, the API returns `429 Too Many Requests` status code. ## Best Practices - Use batch evaluation (`/evaluation/batch`) when evaluating multiple flags for multiple entities - Use `enableDebug: true` only in development environments - Preload flags with `preload=true` parameter when fetching flags to reduce subsequent API calls - Use tags to organize and filter flags efficiently 

API version: 0.1.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateSegmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSegmentRequest{}

// CreateSegmentRequest struct for CreateSegmentRequest
type CreateSegmentRequest struct {
	Description string `json:"description"`
	RolloutPercent int64 `json:"rolloutPercent"`
}

type _CreateSegmentRequest CreateSegmentRequest

// NewCreateSegmentRequest instantiates a new CreateSegmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSegmentRequest(description string, rolloutPercent int64) *CreateSegmentRequest {
	this := CreateSegmentRequest{}
	this.Description = description
	this.RolloutPercent = rolloutPercent
	return &this
}

// NewCreateSegmentRequestWithDefaults instantiates a new CreateSegmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSegmentRequestWithDefaults() *CreateSegmentRequest {
	this := CreateSegmentRequest{}
	return &this
}

// GetDescription returns the Description field value
func (o *CreateSegmentRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreateSegmentRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreateSegmentRequest) SetDescription(v string) {
	o.Description = v
}

// GetRolloutPercent returns the RolloutPercent field value
func (o *CreateSegmentRequest) GetRolloutPercent() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RolloutPercent
}

// GetRolloutPercentOk returns a tuple with the RolloutPercent field value
// and a boolean to check if the value has been set.
func (o *CreateSegmentRequest) GetRolloutPercentOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RolloutPercent, true
}

// SetRolloutPercent sets field value
func (o *CreateSegmentRequest) SetRolloutPercent(v int64) {
	o.RolloutPercent = v
}

func (o CreateSegmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSegmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["rolloutPercent"] = o.RolloutPercent
	return toSerialize, nil
}

func (o *CreateSegmentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"rolloutPercent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateSegmentRequest := _CreateSegmentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateSegmentRequest)

	if err != nil {
		return err
	}

	*o = CreateSegmentRequest(varCreateSegmentRequest)

	return err
}

type NullableCreateSegmentRequest struct {
	value *CreateSegmentRequest
	isSet bool
}

func (v NullableCreateSegmentRequest) Get() *CreateSegmentRequest {
	return v.value
}

func (v *NullableCreateSegmentRequest) Set(val *CreateSegmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSegmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSegmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSegmentRequest(val *CreateSegmentRequest) *NullableCreateSegmentRequest {
	return &NullableCreateSegmentRequest{value: val, isSet: true}
}

func (v NullableCreateSegmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSegmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


