/*
Flagent API

Flagent is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". ## Authentication Flagent supports multiple authentication methods (configured via environment variables): - **JWT Authentication**: Bearer token authentication - **Basic Authentication**: Username/password authentication - **Header Authentication**: Custom header-based authentication - **Cookie Authentication**: Cookie-based authentication Some endpoints (like `/health`, `/evaluation`) may be whitelisted and don't require authentication. ## Error Responses All error responses follow the same format: ```json {   \"message\": \"Error description\" } ``` Common HTTP status codes: - `200`: Success - `400`: Bad Request - invalid input parameters - `404`: Not Found - resource doesn't exist - `429`: Too Many Requests - rate limit exceeded - `500`: Internal Server Error - server error ## Rate Limiting Rate limiting is configured via environment variables: - `FLAGENT_RATELIMITER_PERFLAG_PERSECOND_CONSOLE_LOGGING`: Maximum evaluations per flag per second (default: 100) When rate limit is exceeded, the API returns `429 Too Many Requests` status code. ## Best Practices - Use batch evaluation (`/evaluation/batch`) when evaluating multiple flags for multiple entities - Use `enableDebug: true` only in development environments - Preload flags with `preload=true` parameter when fetching flags to reduce subsequent API calls - Use tags to organize and filter flags efficiently 

API version: 0.1.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Distribution type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Distribution{}

// Distribution struct for Distribution
type Distribution struct {
	Id int64 `json:"id"`
	SegmentID int64 `json:"segmentID"`
	VariantID int64 `json:"variantID"`
	VariantKey NullableString `json:"variantKey,omitempty"`
	Percent int64 `json:"percent"`
}

type _Distribution Distribution

// NewDistribution instantiates a new Distribution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistribution(id int64, segmentID int64, variantID int64, percent int64) *Distribution {
	this := Distribution{}
	this.Id = id
	this.SegmentID = segmentID
	this.VariantID = variantID
	this.Percent = percent
	return &this
}

// NewDistributionWithDefaults instantiates a new Distribution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributionWithDefaults() *Distribution {
	this := Distribution{}
	return &this
}

// GetId returns the Id field value
func (o *Distribution) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Distribution) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Distribution) SetId(v int64) {
	o.Id = v
}

// GetSegmentID returns the SegmentID field value
func (o *Distribution) GetSegmentID() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SegmentID
}

// GetSegmentIDOk returns a tuple with the SegmentID field value
// and a boolean to check if the value has been set.
func (o *Distribution) GetSegmentIDOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SegmentID, true
}

// SetSegmentID sets field value
func (o *Distribution) SetSegmentID(v int64) {
	o.SegmentID = v
}

// GetVariantID returns the VariantID field value
func (o *Distribution) GetVariantID() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.VariantID
}

// GetVariantIDOk returns a tuple with the VariantID field value
// and a boolean to check if the value has been set.
func (o *Distribution) GetVariantIDOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VariantID, true
}

// SetVariantID sets field value
func (o *Distribution) SetVariantID(v int64) {
	o.VariantID = v
}

// GetVariantKey returns the VariantKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Distribution) GetVariantKey() string {
	if o == nil || IsNil(o.VariantKey.Get()) {
		var ret string
		return ret
	}
	return *o.VariantKey.Get()
}

// GetVariantKeyOk returns a tuple with the VariantKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Distribution) GetVariantKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VariantKey.Get(), o.VariantKey.IsSet()
}

// HasVariantKey returns a boolean if a field has been set.
func (o *Distribution) HasVariantKey() bool {
	if o != nil && o.VariantKey.IsSet() {
		return true
	}

	return false
}

// SetVariantKey gets a reference to the given NullableString and assigns it to the VariantKey field.
func (o *Distribution) SetVariantKey(v string) {
	o.VariantKey.Set(&v)
}
// SetVariantKeyNil sets the value for VariantKey to be an explicit nil
func (o *Distribution) SetVariantKeyNil() {
	o.VariantKey.Set(nil)
}

// UnsetVariantKey ensures that no value is present for VariantKey, not even an explicit nil
func (o *Distribution) UnsetVariantKey() {
	o.VariantKey.Unset()
}

// GetPercent returns the Percent field value
func (o *Distribution) GetPercent() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Percent
}

// GetPercentOk returns a tuple with the Percent field value
// and a boolean to check if the value has been set.
func (o *Distribution) GetPercentOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Percent, true
}

// SetPercent sets field value
func (o *Distribution) SetPercent(v int64) {
	o.Percent = v
}

func (o Distribution) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Distribution) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["segmentID"] = o.SegmentID
	toSerialize["variantID"] = o.VariantID
	if o.VariantKey.IsSet() {
		toSerialize["variantKey"] = o.VariantKey.Get()
	}
	toSerialize["percent"] = o.Percent
	return toSerialize, nil
}

func (o *Distribution) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"segmentID",
		"variantID",
		"percent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistribution := _Distribution{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistribution)

	if err != nil {
		return err
	}

	*o = Distribution(varDistribution)

	return err
}

type NullableDistribution struct {
	value *Distribution
	isSet bool
}

func (v NullableDistribution) Get() *Distribution {
	return v.value
}

func (v *NullableDistribution) Set(val *Distribution) {
	v.value = val
	v.isSet = true
}

func (v NullableDistribution) IsSet() bool {
	return v.isSet
}

func (v *NullableDistribution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistribution(val *Distribution) *NullableDistribution {
	return &NullableDistribution{value: val, isSet: true}
}

func (v NullableDistribution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistribution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


