/*
 * Flagent API
 * Flagent is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". ## Authentication Flagent supports multiple authentication methods (configured via environment variables): - **JWT Authentication**: Bearer token authentication - **Basic Authentication**: Username/password authentication - **Header Authentication**: Custom header-based authentication - **Cookie Authentication**: Cookie-based authentication Some endpoints (like `/health`, `/evaluation`) may be whitelisted and don't require authentication. ## Error Responses All error responses follow the same format: ```json {   \"message\": \"Error description\" } ``` Common HTTP status codes: - `200`: Success - `400`: Bad Request - invalid input parameters - `404`: Not Found - resource doesn't exist - `429`: Too Many Requests - rate limit exceeded - `500`: Internal Server Error - server error ## Rate Limiting Rate limiting is configured via environment variables: - `FLAGENT_RATELIMITER_PERFLAG_PERSECOND_CONSOLE_LOGGING`: Maximum evaluations per flag per second (default: 100) When rate limit is exceeded, the API returns `429 Too Many Requests` status code. ## Best Practices - Use batch evaluation (`/evaluation/batch`) when evaluating multiple flags for multiple entities - Use `enableDebug: true` only in development environments - Preload flags with `preload=true` parameter when fetching flags to reduce subsequent API calls - Use tags to organize and filter flags efficiently 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.flagent.client.api;

import com.flagent.client.ApiException;
import com.flagent.client.model.CreateTagRequest;
import com.flagent.client.model.Error;
import com.flagent.client.model.Tag;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for TagApi
 */
@Disabled
public class TagApiTest {

    private final TagApi api = new TagApi();

    
    /**
     * Create tag and associate with flag
     *
     * Create a tag and associate it with the flag. Tags are used for organizing and filtering flags.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createFlagTagTest() throws ApiException {
        Long flagId = null;
        CreateTagRequest createTagRequest = null;
        Tag response = 
        api.createFlagTag(flagId, createTagRequest);
        
        // TODO: test validations
    }
    
    /**
     * Remove tag from flag
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFlagTagTest() throws ApiException {
        Long flagId = null;
        Long tagId = null;
        
        api.deleteFlagTag(flagId, tagId);
        
        // TODO: test validations
    }
    
    /**
     * Get all tags
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllTagsTest() throws ApiException {
        Long limit = null;
        Long offset = null;
        String valueLike = null;
        List<Tag> response = 
        api.findAllTags(limit, offset, valueLike);
        
        // TODO: test validations
    }
    
    /**
     * Get tags for flag
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findFlagTagsTest() throws ApiException {
        Long flagId = null;
        List<Tag> response = 
        api.findFlagTags(flagId);
        
        // TODO: test validations
    }
    
}
