/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param `property` 
 * @param `operator` 
 * @param `value` 
 */
@Serializable

data class CreateConstraintRequest (

    @SerialName(value = "property")
    val `property`: kotlin.String,

    @SerialName(value = "operator")
    val `operator`: kotlin.String,

    @SerialName(value = "value")
    val `value`: kotlin.String

) {


}

