/*
 * Flagent API
 * Flagent is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". ## Authentication Flagent supports multiple authentication methods (configured via environment variables): - **JWT Authentication**: Bearer token authentication - **Basic Authentication**: Username/password authentication - **Header Authentication**: Custom header-based authentication - **Cookie Authentication**: Cookie-based authentication Some endpoints (like `/health`, `/evaluation`) may be whitelisted and don't require authentication. ## Error Responses All error responses follow the same format: ```json {   \"message\": \"Error description\" } ``` Common HTTP status codes: - `200`: Success - `400`: Bad Request - invalid input parameters - `404`: Not Found - resource doesn't exist - `429`: Too Many Requests - rate limit exceeded - `500`: Internal Server Error - server error ## Rate Limiting Rate limiting is configured via environment variables: - `FLAGENT_RATELIMITER_PERFLAG_PERSECOND_CONSOLE_LOGGING`: Maximum evaluations per flag per second (default: 100) When rate limit is exceeded, the API returns `429 Too Many Requests` status code. ## Best Practices - Use batch evaluation (`/evaluation/batch`) when evaluating multiple flags for multiple entities - Use `enableDebug: true` only in development environments - Preload flags with `preload=true` parameter when fetching flags to reduce subsequent API calls - Use tags to organize and filter flags efficiently 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.flagent.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.flagent.client.ApiClient;
/**
 * Constraint
 */
@JsonPropertyOrder({
  Constraint.JSON_PROPERTY_ID,
  Constraint.JSON_PROPERTY_SEGMENT_I_D,
  Constraint.JSON_PROPERTY_PROPERTY,
  Constraint.JSON_PROPERTY_OPERATOR,
  Constraint.JSON_PROPERTY_VALUE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class Constraint {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private Long id;

  public static final String JSON_PROPERTY_SEGMENT_I_D = "segmentID";
  @jakarta.annotation.Nonnull
  private Long segmentID;

  public static final String JSON_PROPERTY_PROPERTY = "property";
  @jakarta.annotation.Nonnull
  private String property;

  /**
   * Gets or Sets operator
   */
  public enum OperatorEnum {
    EQ(String.valueOf("EQ")),
    
    NEQ(String.valueOf("NEQ")),
    
    LT(String.valueOf("LT")),
    
    LTE(String.valueOf("LTE")),
    
    GT(String.valueOf("GT")),
    
    GTE(String.valueOf("GTE")),
    
    EREG(String.valueOf("EREG")),
    
    NEREG(String.valueOf("NEREG")),
    
    IN(String.valueOf("IN")),
    
    NOTIN(String.valueOf("NOTIN")),
    
    CONTAINS(String.valueOf("CONTAINS")),
    
    NOTCONTAINS(String.valueOf("NOTCONTAINS"));

    private String value;

    OperatorEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OperatorEnum fromValue(String value) {
      for (OperatorEnum b : OperatorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OPERATOR = "operator";
  @jakarta.annotation.Nonnull
  private OperatorEnum operator;

  public static final String JSON_PROPERTY_VALUE = "value";
  @jakarta.annotation.Nonnull
  private String value;

  public Constraint() { 
  }

  public Constraint id(@jakarta.annotation.Nonnull Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * minimum: 1
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull Long id) {
    this.id = id;
  }


  public Constraint segmentID(@jakarta.annotation.Nonnull Long segmentID) {
    this.segmentID = segmentID;
    return this;
  }

  /**
   * Get segmentID
   * @return segmentID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SEGMENT_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getSegmentID() {
    return segmentID;
  }


  @JsonProperty(value = JSON_PROPERTY_SEGMENT_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSegmentID(@jakarta.annotation.Nonnull Long segmentID) {
    this.segmentID = segmentID;
  }


  public Constraint property(@jakarta.annotation.Nonnull String property) {
    this.property = property;
    return this;
  }

  /**
   * Get property
   * @return property
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROPERTY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProperty() {
    return property;
  }


  @JsonProperty(value = JSON_PROPERTY_PROPERTY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProperty(@jakarta.annotation.Nonnull String property) {
    this.property = property;
  }


  public Constraint operator(@jakarta.annotation.Nonnull OperatorEnum operator) {
    this.operator = operator;
    return this;
  }

  /**
   * Get operator
   * @return operator
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OPERATOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OperatorEnum getOperator() {
    return operator;
  }


  @JsonProperty(value = JSON_PROPERTY_OPERATOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOperator(@jakarta.annotation.Nonnull OperatorEnum operator) {
    this.operator = operator;
  }


  public Constraint value(@jakarta.annotation.Nonnull String value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VALUE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValue(@jakarta.annotation.Nonnull String value) {
    this.value = value;
  }


  /**
   * Return true if this Constraint object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Constraint constraint = (Constraint) o;
    return Objects.equals(this.id, constraint.id) &&
        Objects.equals(this.segmentID, constraint.segmentID) &&
        Objects.equals(this.property, constraint.property) &&
        Objects.equals(this.operator, constraint.operator) &&
        Objects.equals(this.value, constraint.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, segmentID, property, operator, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Constraint {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    segmentID: ").append(toIndentedString(segmentID)).append("\n");
    sb.append("    property: ").append(toIndentedString(property)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `segmentID` to the URL query string
    if (getSegmentID() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssegmentID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSegmentID()))));
    }

    // add `property` to the URL query string
    if (getProperty() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproperty%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProperty()))));
    }

    // add `operator` to the URL query string
    if (getOperator() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soperator%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOperator()))));
    }

    // add `value` to the URL query string
    if (getValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svalue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getValue()))));
    }

    return joiner.toString();
  }
}

