/*
 * Flagent API
 * Flagent is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". ## Authentication Flagent supports multiple authentication methods (configured via environment variables): - **JWT Authentication**: Bearer token authentication - **Basic Authentication**: Username/password authentication - **Header Authentication**: Custom header-based authentication - **Cookie Authentication**: Cookie-based authentication Some endpoints (like `/health`, `/evaluation`) may be whitelisted and don't require authentication. ## Error Responses All error responses follow the same format: ```json {   \"message\": \"Error description\" } ``` Common HTTP status codes: - `200`: Success - `400`: Bad Request - invalid input parameters - `404`: Not Found - resource doesn't exist - `429`: Too Many Requests - rate limit exceeded - `500`: Internal Server Error - server error ## Rate Limiting Rate limiting is configured via environment variables: - `FLAGENT_RATELIMITER_PERFLAG_PERSECOND_CONSOLE_LOGGING`: Maximum evaluations per flag per second (default: 100) When rate limit is exceeded, the API returns `429 Too Many Requests` status code. ## Best Practices - Use batch evaluation (`/evaluation/batch`) when evaluating multiple flags for multiple entities - Use `enableDebug: true` only in development environments - Preload flags with `preload=true` parameter when fetching flags to reduce subsequent API calls - Use tags to organize and filter flags efficiently 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.flagent.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flagent.client.model.EvalContext;
import com.flagent.client.model.EvalDebugLog;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.flagent.client.ApiClient;
/**
 * EvalResult
 */
@JsonPropertyOrder({
  EvalResult.JSON_PROPERTY_FLAG_I_D,
  EvalResult.JSON_PROPERTY_FLAG_KEY,
  EvalResult.JSON_PROPERTY_FLAG_SNAPSHOT_I_D,
  EvalResult.JSON_PROPERTY_FLAG_TAGS,
  EvalResult.JSON_PROPERTY_SEGMENT_I_D,
  EvalResult.JSON_PROPERTY_VARIANT_I_D,
  EvalResult.JSON_PROPERTY_VARIANT_KEY,
  EvalResult.JSON_PROPERTY_VARIANT_ATTACHMENT,
  EvalResult.JSON_PROPERTY_EVAL_CONTEXT,
  EvalResult.JSON_PROPERTY_TIMESTAMP,
  EvalResult.JSON_PROPERTY_EVAL_DEBUG_LOG
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class EvalResult {
  public static final String JSON_PROPERTY_FLAG_I_D = "flagID";
  @jakarta.annotation.Nullable
  private Long flagID;

  public static final String JSON_PROPERTY_FLAG_KEY = "flagKey";
  @jakarta.annotation.Nullable
  private String flagKey;

  public static final String JSON_PROPERTY_FLAG_SNAPSHOT_I_D = "flagSnapshotID";
  @jakarta.annotation.Nullable
  private Long flagSnapshotID;

  public static final String JSON_PROPERTY_FLAG_TAGS = "flagTags";
  private JsonNullable<List<String>> flagTags = JsonNullable.<List<String>>undefined();

  public static final String JSON_PROPERTY_SEGMENT_I_D = "segmentID";
  private JsonNullable<Long> segmentID = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_VARIANT_I_D = "variantID";
  private JsonNullable<Long> variantID = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_VARIANT_KEY = "variantKey";
  private JsonNullable<String> variantKey = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_VARIANT_ATTACHMENT = "variantAttachment";
  private JsonNullable<Map<String, Object>> variantAttachment = JsonNullable.<Map<String, Object>>undefined();

  public static final String JSON_PROPERTY_EVAL_CONTEXT = "evalContext";
  @jakarta.annotation.Nullable
  private EvalContext evalContext;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @jakarta.annotation.Nullable
  private OffsetDateTime timestamp;

  public static final String JSON_PROPERTY_EVAL_DEBUG_LOG = "evalDebugLog";
  @jakarta.annotation.Nullable
  private EvalDebugLog evalDebugLog;

  public EvalResult() { 
  }

  public EvalResult flagID(@jakarta.annotation.Nullable Long flagID) {
    this.flagID = flagID;
    return this;
  }

  /**
   * Get flagID
   * @return flagID
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FLAG_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getFlagID() {
    return flagID;
  }


  @JsonProperty(value = JSON_PROPERTY_FLAG_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlagID(@jakarta.annotation.Nullable Long flagID) {
    this.flagID = flagID;
  }


  public EvalResult flagKey(@jakarta.annotation.Nullable String flagKey) {
    this.flagKey = flagKey;
    return this;
  }

  /**
   * Get flagKey
   * @return flagKey
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FLAG_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFlagKey() {
    return flagKey;
  }


  @JsonProperty(value = JSON_PROPERTY_FLAG_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlagKey(@jakarta.annotation.Nullable String flagKey) {
    this.flagKey = flagKey;
  }


  public EvalResult flagSnapshotID(@jakarta.annotation.Nullable Long flagSnapshotID) {
    this.flagSnapshotID = flagSnapshotID;
    return this;
  }

  /**
   * Get flagSnapshotID
   * @return flagSnapshotID
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FLAG_SNAPSHOT_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getFlagSnapshotID() {
    return flagSnapshotID;
  }


  @JsonProperty(value = JSON_PROPERTY_FLAG_SNAPSHOT_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlagSnapshotID(@jakarta.annotation.Nullable Long flagSnapshotID) {
    this.flagSnapshotID = flagSnapshotID;
  }


  public EvalResult flagTags(@jakarta.annotation.Nullable List<String> flagTags) {
    this.flagTags = JsonNullable.<List<String>>of(flagTags);
    return this;
  }

  public EvalResult addFlagTagsItem(String flagTagsItem) {
    if (this.flagTags == null || !this.flagTags.isPresent()) {
      this.flagTags = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.flagTags.get().add(flagTagsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get flagTags
   * @return flagTags
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<String> getFlagTags() {
        return flagTags.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FLAG_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getFlagTags_JsonNullable() {
    return flagTags;
  }
  
  @JsonProperty(JSON_PROPERTY_FLAG_TAGS)
  public void setFlagTags_JsonNullable(JsonNullable<List<String>> flagTags) {
    this.flagTags = flagTags;
  }

  public void setFlagTags(@jakarta.annotation.Nullable List<String> flagTags) {
    this.flagTags = JsonNullable.<List<String>>of(flagTags);
  }


  public EvalResult segmentID(@jakarta.annotation.Nullable Long segmentID) {
    this.segmentID = JsonNullable.<Long>of(segmentID);
    return this;
  }

  /**
   * Get segmentID
   * @return segmentID
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Long getSegmentID() {
        return segmentID.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SEGMENT_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getSegmentID_JsonNullable() {
    return segmentID;
  }
  
  @JsonProperty(JSON_PROPERTY_SEGMENT_I_D)
  public void setSegmentID_JsonNullable(JsonNullable<Long> segmentID) {
    this.segmentID = segmentID;
  }

  public void setSegmentID(@jakarta.annotation.Nullable Long segmentID) {
    this.segmentID = JsonNullable.<Long>of(segmentID);
  }


  public EvalResult variantID(@jakarta.annotation.Nullable Long variantID) {
    this.variantID = JsonNullable.<Long>of(variantID);
    return this;
  }

  /**
   * Get variantID
   * @return variantID
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Long getVariantID() {
        return variantID.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_VARIANT_I_D, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getVariantID_JsonNullable() {
    return variantID;
  }
  
  @JsonProperty(JSON_PROPERTY_VARIANT_I_D)
  public void setVariantID_JsonNullable(JsonNullable<Long> variantID) {
    this.variantID = variantID;
  }

  public void setVariantID(@jakarta.annotation.Nullable Long variantID) {
    this.variantID = JsonNullable.<Long>of(variantID);
  }


  public EvalResult variantKey(@jakarta.annotation.Nullable String variantKey) {
    this.variantKey = JsonNullable.<String>of(variantKey);
    return this;
  }

  /**
   * Get variantKey
   * @return variantKey
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getVariantKey() {
        return variantKey.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_VARIANT_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getVariantKey_JsonNullable() {
    return variantKey;
  }
  
  @JsonProperty(JSON_PROPERTY_VARIANT_KEY)
  public void setVariantKey_JsonNullable(JsonNullable<String> variantKey) {
    this.variantKey = variantKey;
  }

  public void setVariantKey(@jakarta.annotation.Nullable String variantKey) {
    this.variantKey = JsonNullable.<String>of(variantKey);
  }


  public EvalResult variantAttachment(@jakarta.annotation.Nullable Map<String, Object> variantAttachment) {
    this.variantAttachment = JsonNullable.<Map<String, Object>>of(variantAttachment);
    return this;
  }

  public EvalResult putVariantAttachmentItem(String key, Object variantAttachmentItem) {
    if (this.variantAttachment == null || !this.variantAttachment.isPresent()) {
      this.variantAttachment = JsonNullable.<Map<String, Object>>of(new HashMap<>());
    }
    try {
      this.variantAttachment.get().put(key, variantAttachmentItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get variantAttachment
   * @return variantAttachment
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Map<String, Object> getVariantAttachment() {
        return variantAttachment.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_VARIANT_ATTACHMENT, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Object>> getVariantAttachment_JsonNullable() {
    return variantAttachment;
  }
  
  @JsonProperty(JSON_PROPERTY_VARIANT_ATTACHMENT)
  public void setVariantAttachment_JsonNullable(JsonNullable<Map<String, Object>> variantAttachment) {
    this.variantAttachment = variantAttachment;
  }

  public void setVariantAttachment(@jakarta.annotation.Nullable Map<String, Object> variantAttachment) {
    this.variantAttachment = JsonNullable.<Map<String, Object>>of(variantAttachment);
  }


  public EvalResult evalContext(@jakarta.annotation.Nullable EvalContext evalContext) {
    this.evalContext = evalContext;
    return this;
  }

  /**
   * Get evalContext
   * @return evalContext
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVAL_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EvalContext getEvalContext() {
    return evalContext;
  }


  @JsonProperty(value = JSON_PROPERTY_EVAL_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvalContext(@jakarta.annotation.Nullable EvalContext evalContext) {
    this.evalContext = evalContext;
  }


  public EvalResult timestamp(@jakarta.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@jakarta.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public EvalResult evalDebugLog(@jakarta.annotation.Nullable EvalDebugLog evalDebugLog) {
    this.evalDebugLog = evalDebugLog;
    return this;
  }

  /**
   * Get evalDebugLog
   * @return evalDebugLog
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVAL_DEBUG_LOG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EvalDebugLog getEvalDebugLog() {
    return evalDebugLog;
  }


  @JsonProperty(value = JSON_PROPERTY_EVAL_DEBUG_LOG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvalDebugLog(@jakarta.annotation.Nullable EvalDebugLog evalDebugLog) {
    this.evalDebugLog = evalDebugLog;
  }


  /**
   * Return true if this EvalResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvalResult evalResult = (EvalResult) o;
    return Objects.equals(this.flagID, evalResult.flagID) &&
        Objects.equals(this.flagKey, evalResult.flagKey) &&
        Objects.equals(this.flagSnapshotID, evalResult.flagSnapshotID) &&
        equalsNullable(this.flagTags, evalResult.flagTags) &&
        equalsNullable(this.segmentID, evalResult.segmentID) &&
        equalsNullable(this.variantID, evalResult.variantID) &&
        equalsNullable(this.variantKey, evalResult.variantKey) &&
        equalsNullable(this.variantAttachment, evalResult.variantAttachment) &&
        Objects.equals(this.evalContext, evalResult.evalContext) &&
        Objects.equals(this.timestamp, evalResult.timestamp) &&
        Objects.equals(this.evalDebugLog, evalResult.evalDebugLog);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(flagID, flagKey, flagSnapshotID, hashCodeNullable(flagTags), hashCodeNullable(segmentID), hashCodeNullable(variantID), hashCodeNullable(variantKey), hashCodeNullable(variantAttachment), evalContext, timestamp, evalDebugLog);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvalResult {\n");
    sb.append("    flagID: ").append(toIndentedString(flagID)).append("\n");
    sb.append("    flagKey: ").append(toIndentedString(flagKey)).append("\n");
    sb.append("    flagSnapshotID: ").append(toIndentedString(flagSnapshotID)).append("\n");
    sb.append("    flagTags: ").append(toIndentedString(flagTags)).append("\n");
    sb.append("    segmentID: ").append(toIndentedString(segmentID)).append("\n");
    sb.append("    variantID: ").append(toIndentedString(variantID)).append("\n");
    sb.append("    variantKey: ").append(toIndentedString(variantKey)).append("\n");
    sb.append("    variantAttachment: ").append(toIndentedString(variantAttachment)).append("\n");
    sb.append("    evalContext: ").append(toIndentedString(evalContext)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    evalDebugLog: ").append(toIndentedString(evalDebugLog)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `flagID` to the URL query string
    if (getFlagID() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sflagID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFlagID()))));
    }

    // add `flagKey` to the URL query string
    if (getFlagKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sflagKey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFlagKey()))));
    }

    // add `flagSnapshotID` to the URL query string
    if (getFlagSnapshotID() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sflagSnapshotID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFlagSnapshotID()))));
    }

    // add `flagTags` to the URL query string
    if (getFlagTags() != null) {
      for (int i = 0; i < getFlagTags().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sflagTags%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getFlagTags().get(i)))));
      }
    }

    // add `segmentID` to the URL query string
    if (getSegmentID() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssegmentID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSegmentID()))));
    }

    // add `variantID` to the URL query string
    if (getVariantID() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svariantID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVariantID()))));
    }

    // add `variantKey` to the URL query string
    if (getVariantKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svariantKey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVariantKey()))));
    }

    // add `variantAttachment` to the URL query string
    if (getVariantAttachment() != null) {
      for (String _key : getVariantAttachment().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%svariantAttachment%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getVariantAttachment().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getVariantAttachment().get(_key)))));
      }
    }

    // add `evalContext` to the URL query string
    if (getEvalContext() != null) {
      joiner.add(getEvalContext().toUrlQueryString(prefix + "evalContext" + suffix));
    }

    // add `timestamp` to the URL query string
    if (getTimestamp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimestamp()))));
    }

    // add `evalDebugLog` to the URL query string
    if (getEvalDebugLog() != null) {
      joiner.add(getEvalDebugLog().toUrlQueryString(prefix + "evalDebugLog" + suffix));
    }

    return joiner.toString();
  }
}

