/*
 * Flagent API
 * Flagent is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". ## Authentication Flagent supports multiple authentication methods (configured via environment variables): - **JWT Authentication**: Bearer token authentication - **Basic Authentication**: Username/password authentication - **Header Authentication**: Custom header-based authentication - **Cookie Authentication**: Cookie-based authentication Some endpoints (like `/health`, `/evaluation`) may be whitelisted and don't require authentication. ## Error Responses All error responses follow the same format: ```json {   \"message\": \"Error description\" } ``` Common HTTP status codes: - `200`: Success - `400`: Bad Request - invalid input parameters - `404`: Not Found - resource doesn't exist - `429`: Too Many Requests - rate limit exceeded - `500`: Internal Server Error - server error ## Rate Limiting Rate limiting is configured via environment variables: - `FLAGENT_RATELIMITER_PERFLAG_PERSECOND_CONSOLE_LOGGING`: Maximum evaluations per flag per second (default: 100) When rate limit is exceeded, the API returns `429 Too Many Requests` status code. ## Best Practices - Use batch evaluation (`/evaluation/batch`) when evaluating multiple flags for multiple entities - Use `enableDebug: true` only in development environments - Preload flags with `preload=true` parameter when fetching flags to reduce subsequent API calls - Use tags to organize and filter flags efficiently 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.flagent.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flagent.client.model.SegmentDebugLog;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.flagent.client.ApiClient;
/**
 * EvalDebugLog
 */
@JsonPropertyOrder({
  EvalDebugLog.JSON_PROPERTY_MSG,
  EvalDebugLog.JSON_PROPERTY_SEGMENT_DEBUG_LOGS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class EvalDebugLog {
  public static final String JSON_PROPERTY_MSG = "msg";
  @jakarta.annotation.Nullable
  private String msg;

  public static final String JSON_PROPERTY_SEGMENT_DEBUG_LOGS = "segmentDebugLogs";
  @jakarta.annotation.Nullable
  private List<SegmentDebugLog> segmentDebugLogs = new ArrayList<>();

  public EvalDebugLog() { 
  }

  public EvalDebugLog msg(@jakarta.annotation.Nullable String msg) {
    this.msg = msg;
    return this;
  }

  /**
   * Get msg
   * @return msg
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MSG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMsg() {
    return msg;
  }


  @JsonProperty(value = JSON_PROPERTY_MSG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMsg(@jakarta.annotation.Nullable String msg) {
    this.msg = msg;
  }


  public EvalDebugLog segmentDebugLogs(@jakarta.annotation.Nullable List<SegmentDebugLog> segmentDebugLogs) {
    this.segmentDebugLogs = segmentDebugLogs;
    return this;
  }

  public EvalDebugLog addSegmentDebugLogsItem(SegmentDebugLog segmentDebugLogsItem) {
    if (this.segmentDebugLogs == null) {
      this.segmentDebugLogs = new ArrayList<>();
    }
    this.segmentDebugLogs.add(segmentDebugLogsItem);
    return this;
  }

  /**
   * Get segmentDebugLogs
   * @return segmentDebugLogs
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEGMENT_DEBUG_LOGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<SegmentDebugLog> getSegmentDebugLogs() {
    return segmentDebugLogs;
  }


  @JsonProperty(value = JSON_PROPERTY_SEGMENT_DEBUG_LOGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSegmentDebugLogs(@jakarta.annotation.Nullable List<SegmentDebugLog> segmentDebugLogs) {
    this.segmentDebugLogs = segmentDebugLogs;
  }


  /**
   * Return true if this EvalDebugLog object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvalDebugLog evalDebugLog = (EvalDebugLog) o;
    return Objects.equals(this.msg, evalDebugLog.msg) &&
        Objects.equals(this.segmentDebugLogs, evalDebugLog.segmentDebugLogs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(msg, segmentDebugLogs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvalDebugLog {\n");
    sb.append("    msg: ").append(toIndentedString(msg)).append("\n");
    sb.append("    segmentDebugLogs: ").append(toIndentedString(segmentDebugLogs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `msg` to the URL query string
    if (getMsg() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smsg%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMsg()))));
    }

    // add `segmentDebugLogs` to the URL query string
    if (getSegmentDebugLogs() != null) {
      for (int i = 0; i < getSegmentDebugLogs().size(); i++) {
        if (getSegmentDebugLogs().get(i) != null) {
          joiner.add(getSegmentDebugLogs().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%ssegmentDebugLogs%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

