/*
 * Flagent API
 * Flagent is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". ## Authentication Flagent supports multiple authentication methods (configured via environment variables): - **JWT Authentication**: Bearer token authentication - **Basic Authentication**: Username/password authentication - **Header Authentication**: Custom header-based authentication - **Cookie Authentication**: Cookie-based authentication Some endpoints (like `/health`, `/evaluation`) may be whitelisted and don't require authentication. ## Error Responses All error responses follow the same format: ```json {   \"message\": \"Error description\" } ``` Common HTTP status codes: - `200`: Success - `400`: Bad Request - invalid input parameters - `404`: Not Found - resource doesn't exist - `429`: Too Many Requests - rate limit exceeded - `500`: Internal Server Error - server error ## Rate Limiting Rate limiting is configured via environment variables: - `FLAGENT_RATELIMITER_PERFLAG_PERSECOND_CONSOLE_LOGGING`: Maximum evaluations per flag per second (default: 100) When rate limit is exceeded, the API returns `429 Too Many Requests` status code. ## Best Practices - Use batch evaluation (`/evaluation/batch`) when evaluating multiple flags for multiple entities - Use `enableDebug: true` only in development environments - Preload flags with `preload=true` parameter when fetching flags to reduce subsequent API calls - Use tags to organize and filter flags efficiently 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.flagent.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.flagent.client.ApiClient;
/**
 * Variant
 */
@JsonPropertyOrder({
  Variant.JSON_PROPERTY_ID,
  Variant.JSON_PROPERTY_FLAG_I_D,
  Variant.JSON_PROPERTY_KEY,
  Variant.JSON_PROPERTY_ATTACHMENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class Variant {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private Long id;

  public static final String JSON_PROPERTY_FLAG_I_D = "flagID";
  @jakarta.annotation.Nonnull
  private Long flagID;

  public static final String JSON_PROPERTY_KEY = "key";
  @jakarta.annotation.Nonnull
  private String key;

  public static final String JSON_PROPERTY_ATTACHMENT = "attachment";
  private JsonNullable<Map<String, Object>> attachment = JsonNullable.<Map<String, Object>>undefined();

  public Variant() { 
  }

  public Variant id(@jakarta.annotation.Nonnull Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * minimum: 1
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull Long id) {
    this.id = id;
  }


  public Variant flagID(@jakarta.annotation.Nonnull Long flagID) {
    this.flagID = flagID;
    return this;
  }

  /**
   * Get flagID
   * @return flagID
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FLAG_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getFlagID() {
    return flagID;
  }


  @JsonProperty(value = JSON_PROPERTY_FLAG_I_D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFlagID(@jakarta.annotation.Nonnull Long flagID) {
    this.flagID = flagID;
  }


  public Variant key(@jakarta.annotation.Nonnull String key) {
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getKey() {
    return key;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKey(@jakarta.annotation.Nonnull String key) {
    this.key = key;
  }


  public Variant attachment(@jakarta.annotation.Nullable Map<String, Object> attachment) {
    this.attachment = JsonNullable.<Map<String, Object>>of(attachment);
    return this;
  }

  public Variant putAttachmentItem(String key, Object attachmentItem) {
    if (this.attachment == null || !this.attachment.isPresent()) {
      this.attachment = JsonNullable.<Map<String, Object>>of(new HashMap<>());
    }
    try {
      this.attachment.get().put(key, attachmentItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get attachment
   * @return attachment
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Map<String, Object> getAttachment() {
        return attachment.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ATTACHMENT, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Object>> getAttachment_JsonNullable() {
    return attachment;
  }
  
  @JsonProperty(JSON_PROPERTY_ATTACHMENT)
  public void setAttachment_JsonNullable(JsonNullable<Map<String, Object>> attachment) {
    this.attachment = attachment;
  }

  public void setAttachment(@jakarta.annotation.Nullable Map<String, Object> attachment) {
    this.attachment = JsonNullable.<Map<String, Object>>of(attachment);
  }


  /**
   * Return true if this Variant object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Variant variant = (Variant) o;
    return Objects.equals(this.id, variant.id) &&
        Objects.equals(this.flagID, variant.flagID) &&
        Objects.equals(this.key, variant.key) &&
        equalsNullable(this.attachment, variant.attachment);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, flagID, key, hashCodeNullable(attachment));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Variant {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    flagID: ").append(toIndentedString(flagID)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    attachment: ").append(toIndentedString(attachment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `flagID` to the URL query string
    if (getFlagID() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sflagID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFlagID()))));
    }

    // add `key` to the URL query string
    if (getKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKey()))));
    }

    // add `attachment` to the URL query string
    if (getAttachment() != null) {
      for (String _key : getAttachment().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sattachment%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getAttachment().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getAttachment().get(_key)))));
      }
    }

    return joiner.toString();
  }
}

