package flagent.route

import flagent.application.module
import flagent.repository.Database
import io.ktor.client.call.*
import io.ktor.client.plugins.contentnegotiation.*
import io.ktor.client.request.*
import io.ktor.http.*
import io.ktor.serialization.kotlinx.json.*
import io.ktor.server.testing.*
import kotlinx.serialization.json.Json
import kotlin.test.*

/**
 * Integration tests for Flag routes
 * Tests complete API workflow with real database operations
 */
class FlagRoutesIntegrationTest {
    
    @BeforeTest
    fun setup() {
        Database.init()
    }
    
    @AfterTest
    fun cleanup() {
        Database.close()
    }
    
    @Test
    fun testFlagCRUD_FullCycle() = testApplication {
        application {
            module()
        }
        
        val client = createClient {
            install(ContentNegotiation) {
                json(Json { ignoreUnknownKeys = true })
            }
        }
        
        try {
            // CREATE
            val createResponse = client.post("/api/v1/flags") {
                contentType(ContentType.Application.Json)
                setBody(mapOf(
                    "description" to "Integration test flag",
                    "key" to "integration_test_flag"
                ))
            }
            
            assertEquals(HttpStatusCode.OK, createResponse.status)
            val createdFlag = createResponse.body<Map<String, Any>>()
            val flagId = (createdFlag["id"] as Number).toInt()
            assertTrue(flagId > 0)
            assertEquals("integration_test_flag", createdFlag["key"])
            assertEquals("Integration test flag", createdFlag["description"])
            assertEquals(false, createdFlag["enabled"])
            
            // READ - Get by ID
            val getResponse = client.get("/api/v1/flags/$flagId")
            assertEquals(HttpStatusCode.OK, getResponse.status)
            val fetchedFlag = getResponse.body<Map<String, Any>>()
            assertEquals(flagId, (fetchedFlag["id"] as Number).toInt())
            
            // UPDATE
            val updateResponse = client.put("/api/v1/flags/$flagId") {
                contentType(ContentType.Application.Json)
                setBody(mapOf(
                    "description" to "Updated integration test flag",
                    "dataRecordsEnabled" to true
                ))
            }
            
            assertEquals(HttpStatusCode.OK, updateResponse.status)
            val updatedFlag = updateResponse.body<Map<String, Any>>()
            assertEquals("Updated integration test flag", updatedFlag["description"])
            assertEquals(true, updatedFlag["dataRecordsEnabled"])
            
            // ENABLE
            val enableResponse = client.put("/api/v1/flags/$flagId/enabled") {
                contentType(ContentType.Application.Json)
                setBody(mapOf("enabled" to true))
            }
            
            assertEquals(HttpStatusCode.OK, enableResponse.status)
            val enabledFlag = enableResponse.body<Map<String, Any>>()
            assertEquals(true, enabledFlag["enabled"])
            
            // LIST - Verify flag appears in list
            val listResponse = client.get("/api/v1/flags?enabled=true")
            assertEquals(HttpStatusCode.OK, listResponse.status)
            val flags = listResponse.body<List<Map<String, Any>>>()
            assertTrue(flags.any { (it["id"] as Number).toInt() == flagId })
            
            // DELETE
            val deleteResponse = client.delete("/api/v1/flags/$flagId")
            assertEquals(HttpStatusCode.OK, deleteResponse.status)
            
            // Verify deleted - should return 404
            val getDeletedResponse = client.get("/api/v1/flags/$flagId")
            assertEquals(HttpStatusCode.NotFound, getDeletedResponse.status)
            
        } finally {
            client.close()
        }
    }
    
    @Test
    fun testFlagCreation_WithAutoGeneratedKey() = testApplication {
        application {
            module()
        }
        
        val client = createClient {
            install(ContentNegotiation) {
                json(Json { ignoreUnknownKeys = true })
            }
        }
        
        try {
            val response = client.post("/api/v1/flags") {
                contentType(ContentType.Application.Json)
                setBody(mapOf(
                    "description" to "Flag without key"
                ))
            }
            
            assertEquals(HttpStatusCode.OK, response.status)
            val flag = response.body<Map<String, Any>>()
            assertNotNull(flag["key"])
            assertTrue((flag["key"] as String).isNotEmpty())
            assertTrue((flag["key"] as String).startsWith("k"))
        } finally {
            client.close()
        }
    }
    
    @Test
    fun testFlagCreation_WithTemplate() = testApplication {
        application {
            module()
        }
        
        val client = createClient {
            install(ContentNegotiation) {
                json(Json { ignoreUnknownKeys = true })
            }
        }
        
        try {
            val response = client.post("/api/v1/flags") {
                contentType(ContentType.Application.Json)
                setBody(mapOf(
                    "description" to "Simple boolean flag",
                    "key" to "boolean_flag",
                    "template" to "simple_boolean_flag"
                ))
            }
            
            assertEquals(HttpStatusCode.OK, response.status)
            val flag = response.body<Map<String, Any>>()
            val flagId = (flag["id"] as Number).toInt()
            
            // Verify segments were created
            val segmentsResponse = client.get("/api/v1/flags/$flagId/segments")
            assertEquals(HttpStatusCode.OK, segmentsResponse.status)
            val segments = segmentsResponse.body<List<Map<String, Any>>>()
            assertEquals(1, segments.size)
            
            // Verify variants were created
            val variantsResponse = client.get("/api/v1/flags/$flagId/variants")
            assertEquals(HttpStatusCode.OK, variantsResponse.status)
            val variants = variantsResponse.body<List<Map<String, Any>>>()
            assertTrue(variants.any { it["key"] == "on" })
        } finally {
            client.close()
        }
    }
    
    @Test
    fun testFlagQuery_Filters() = testApplication {
        application {
            module()
        }
        
        val client = createClient {
            install(ContentNegotiation) {
                json(Json { ignoreUnknownKeys = true })
            }
        }
        
        try {
            // Create multiple flags
            val flag1 = client.post("/api/v1/flags") {
                contentType(ContentType.Application.Json)
                setBody(mapOf("description" to "Enabled flag", "key" to "enabled_flag"))
            }.body<Map<String, Any>>()
            
            val flag2 = client.post("/api/v1/flags") {
                contentType(ContentType.Application.Json)
                setBody(mapOf("description" to "Disabled flag", "key" to "disabled_flag"))
            }.body<Map<String, Any>>()
            
            val flag1Id = (flag1["id"] as Number).toInt()
            val flag2Id = (flag2["id"] as Number).toInt()
            
            // Enable flag1
            client.put("/api/v1/flags/$flag1Id/enabled") {
                contentType(ContentType.Application.Json)
                setBody(mapOf("enabled" to true))
            }
            
            // Test enabled filter
            val enabledFlags = client.get("/api/v1/flags?enabled=true")
                .body<List<Map<String, Any>>>()
            assertTrue(enabledFlags.any { (it["id"] as Number).toInt() == flag1Id })
            assertFalse(enabledFlags.any { (it["id"] as Number).toInt() == flag2Id })
            
            // Test key filter
            val keyFiltered = client.get("/api/v1/flags?key=enabled_flag")
                .body<List<Map<String, Any>>>()
            assertEquals(1, keyFiltered.size)
            assertEquals("enabled_flag", keyFiltered[0]["key"])
            
            // Test descriptionLike filter
            val descFiltered = client.get("/api/v1/flags?descriptionLike=Enabled")
                .body<List<Map<String, Any>>>()
            assertTrue(descFiltered.any { (it["id"] as Number).toInt() == flag1Id })
            
            // Test limit and offset
            val limited = client.get("/api/v1/flags?limit=1&offset=0")
                .body<List<Map<String, Any>>>()
            assertEquals(1, limited.size)
            
        } finally {
            client.close()
        }
    }
    
    @Test
    fun testFlagUpdate_ValidationErrors() = testApplication {
        application {
            module()
        }
        
        val client = createClient {
            install(ContentNegotiation) {
                json(Json { ignoreUnknownKeys = true })
            }
        }
        
        try {
            // Try to update non-existent flag
            val response = client.put("/api/v1/flags/99999") {
                contentType(ContentType.Application.Json)
                setBody(mapOf("description" to "Test"))
            }
            
            assertEquals(HttpStatusCode.NotFound, response.status)
        } finally {
            client.close()
        }
    }
    
    @Test
    fun testFlagCreation_InvalidKey() = testApplication {
        application {
            module()
        }
        
        val client = createClient {
            install(ContentNegotiation) {
                json(Json { ignoreUnknownKeys = true })
            }
        }
        
        try {
            val response = client.post("/api/v1/flags") {
                contentType(ContentType.Application.Json)
                setBody(mapOf(
                    "description" to "Test flag",
                    "key" to "invalid key with spaces!"
                ))
            }
            
            assertEquals(HttpStatusCode.BadRequest, response.status)
        } finally {
            client.close()
        }
    }
    
    @Test
    fun testFlagGet_NotFound() = testApplication {
        application {
            module()
        }
        
        val client = createClient {
            install(ContentNegotiation) {
                json(Json { ignoreUnknownKeys = true })
            }
        }
        
        try {
            val response = client.get("/api/v1/flags/99999")
            assertEquals(HttpStatusCode.NotFound, response.status)
        } finally {
            client.close()
        }
    }
    
    @Test
    fun testFlagList_EmptyResult() = testApplication {
        application {
            module()
        }
        
        val client = createClient {
            install(ContentNegotiation) {
                json(Json { ignoreUnknownKeys = true })
            }
        }
        
        try {
            val response = client.get("/api/v1/flags?key=non_existent_flag_xyz")
            assertEquals(HttpStatusCode.OK, response.status)
            val flags = response.body<List<Map<String, Any>>>()
            assertTrue(flags.isEmpty())
        } finally {
            client.close()
        }
    }
}
