/*
Flagent API

Testing SegmentAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/MaxLuxs/Flagent/sdk/go/api"
)

func Test_api_SegmentAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SegmentAPIService CreateSegment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var flagId int64

		resp, httpRes, err := apiClient.SegmentAPI.CreateSegment(context.Background(), flagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SegmentAPIService DeleteSegment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var flagId int64
		var segmentId int64

		httpRes, err := apiClient.SegmentAPI.DeleteSegment(context.Background(), flagId, segmentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SegmentAPIService FindSegments", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var flagId int64

		resp, httpRes, err := apiClient.SegmentAPI.FindSegments(context.Background(), flagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SegmentAPIService PutSegment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var flagId int64
		var segmentId int64

		resp, httpRes, err := apiClient.SegmentAPI.PutSegment(context.Background(), flagId, segmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SegmentAPIService PutSegmentReorder", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var flagId int64

		httpRes, err := apiClient.SegmentAPI.PutSegmentReorder(context.Background(), flagId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
