/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

import com.flagent.client.models.CreateTagRequest

class CreateTagRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateTagRequest
        //val modelInstance = CreateTagRequest()

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

    }
}
