/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

import com.flagent.client.models.PutSegmentRequest

class PutSegmentRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PutSegmentRequest
        //val modelInstance = PutSegmentRequest()

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `rolloutPercent`
        should("test rolloutPercent") {
            // uncomment below to test the property
            //modelInstance.rolloutPercent shouldBe ("TODO")
        }

    }
}
