/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

class PutSegmentReorderRequestTest : ShouldSpec() {
    init {
        val modelInstance = PutSegmentReorderRequest(segmentIDs = listOf(1L, 2L, 3L))

        should("test segmentIDs") {
            modelInstance.segmentIDs shouldBe listOf(1L, 2L, 3L)
        }
    }
}
