/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

class PutSegmentRequestTest : ShouldSpec() {
    init {
        val modelInstance = PutSegmentRequest(
            description = "Updated segment",
            rolloutPercent = 75L
        )

        should("test description") {
            modelInstance.description shouldBe "Updated segment"
        }

        should("test rolloutPercent") {
            modelInstance.rolloutPercent shouldBe 75L
        }
    }
}
