/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

import com.flagent.client.models.SetFlagEnabledRequest

class SetFlagEnabledRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SetFlagEnabledRequest
        //val modelInstance = SetFlagEnabledRequest()

        // to test the property `enabled`
        should("test enabled") {
            // uncomment below to test the property
            //modelInstance.enabled shouldBe ("TODO")
        }

    }
}
