/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

class SetFlagEnabledRequestTest : ShouldSpec() {
    init {
        val modelInstance = SetFlagEnabledRequest(enabled = true)

        should("test enabled") {
            modelInstance.enabled shouldBe true
        }
    }
}
