//
// Constraint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct Constraint: Codable, JSONEncodable, Hashable {

    internal enum Operator: String, Codable, CaseIterable {
        case eq = "EQ"
        case neq = "NEQ"
        case lt = "LT"
        case lte = "LTE"
        case gt = "GT"
        case gte = "GTE"
        case ereg = "EREG"
        case nereg = "NEREG"
        case _in = "IN"
        case notin = "NOTIN"
        case contains = "CONTAINS"
        case notcontains = "NOTCONTAINS"
    }
    internal static let idRule = NumericRule<Int64>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    internal static let propertyRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    internal static let valueRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    internal var id: Int64
    internal var segmentID: Int64
    internal var property: String
    internal var _operator: Operator
    internal var value: String

    internal init(id: Int64, segmentID: Int64, property: String, _operator: Operator, value: String) {
        self.id = id
        self.segmentID = segmentID
        self.property = property
        self._operator = _operator
        self.value = value
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case segmentID
        case property
        case _operator = "operator"
        case value
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(segmentID, forKey: .segmentID)
        try container.encode(property, forKey: .property)
        try container.encode(_operator, forKey: ._operator)
        try container.encode(value, forKey: .value)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Constraint: Identifiable {}
