//
// EvaluationBatchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct EvaluationBatchResponse: Codable, JSONEncodable, Hashable {

    internal var evaluationResults: [EvalResult]

    internal init(evaluationResults: [EvalResult]) {
        self.evaluationResults = evaluationResults
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case evaluationResults
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(evaluationResults, forKey: .evaluationResults)
    }
}

