//
// Tag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct Tag: Codable, JSONEncodable, Hashable {

    internal static let idRule = NumericRule<Int64>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    internal static let valueRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    internal var id: Int64
    internal var value: String

    internal init(id: Int64, value: String) {
        self.id = id
        self.value = value
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case value
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(value, forKey: .value)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Tag: Identifiable {}
