/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param variantID 
 * @param percent 
 * @param variantKey 
 */
@Serializable

data class DistributionRequest (

    @SerialName(value = "variantID")
    val variantID: kotlin.Long,

    @SerialName(value = "percent")
    val percent: kotlin.Long,

    @SerialName(value = "variantKey")
    val variantKey: kotlin.String? = null

) {


}

