/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import com.flagent.client.models.EvalContext
import com.flagent.client.models.EvalDebugLog

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param flagID 
 * @param flagKey 
 * @param flagSnapshotID 
 * @param flagTags 
 * @param segmentID 
 * @param variantID 
 * @param variantKey 
 * @param variantAttachment 
 * @param evalContext 
 * @param timestamp 
 * @param evalDebugLog 
 */
@Serializable

data class EvalResult (

    @SerialName(value = "flagID")
    val flagID: kotlin.Long? = null,

    @SerialName(value = "flagKey")
    val flagKey: kotlin.String? = null,

    @SerialName(value = "flagSnapshotID")
    val flagSnapshotID: kotlin.Long? = null,

    @SerialName(value = "flagTags")
    val flagTags: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "segmentID")
    val segmentID: kotlin.Long? = null,

    @SerialName(value = "variantID")
    val variantID: kotlin.Long? = null,

    @SerialName(value = "variantKey")
    val variantKey: kotlin.String? = null,

    @Contextual @SerialName(value = "variantAttachment")
    val variantAttachment: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @SerialName(value = "evalContext")
    val evalContext: EvalContext? = null,

    @Contextual @SerialName(value = "timestamp")
    val timestamp: kotlin.time.Instant? = null,

    @SerialName(value = "evalDebugLog")
    val evalDebugLog: EvalDebugLog? = null

) {


}

