//
// EvaluationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(Combine)
import Combine
#endif
#if canImport(AnyCodable)
import AnyCodable
#endif

open class EvaluationAPI {

    /**
     Evaluate flag
     
     - parameter evalContext: (body)  
     - returns: AnyPublisher<EvalResult, Error>
     */
    #if canImport(Combine)
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func postEvaluation(evalContext: EvalContext) -> AnyPublisher<EvalResult, Error> {
        let requestBuilder = postEvaluationWithRequestBuilder(evalContext: evalContext)
        let requestTask = requestBuilder.requestTask
        return Future<EvalResult, Error> { promise in
            requestBuilder.execute { result in
                switch result {
                case let .success(response):
                    promise(.success(response.body))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }
        .handleEvents(receiveCancel: {
            requestTask.cancel()
        })
        .eraseToAnyPublisher()
    }
    #endif

    /**
     Evaluate flag
     - POST /evaluation
     - parameter evalContext: (body)  
     - returns: RequestBuilder<EvalResult> 
     */
    open class func postEvaluationWithRequestBuilder(evalContext: EvalContext) -> RequestBuilder<EvalResult> {
        let localVariablePath = "/evaluation"
        let localVariableURLString = FlagentClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: evalContext)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EvalResult>.Type = FlagentClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Batch evaluate flags
     
     - parameter evaluationBatchRequest: (body)  
     - returns: AnyPublisher<EvaluationBatchResponse, Error>
     */
    #if canImport(Combine)
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func postEvaluationBatch(evaluationBatchRequest: EvaluationBatchRequest) -> AnyPublisher<EvaluationBatchResponse, Error> {
        let requestBuilder = postEvaluationBatchWithRequestBuilder(evaluationBatchRequest: evaluationBatchRequest)
        let requestTask = requestBuilder.requestTask
        return Future<EvaluationBatchResponse, Error> { promise in
            requestBuilder.execute { result in
                switch result {
                case let .success(response):
                    promise(.success(response.body))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }
        .handleEvents(receiveCancel: {
            requestTask.cancel()
        })
        .eraseToAnyPublisher()
    }
    #endif

    /**
     Batch evaluate flags
     - POST /evaluation/batch
     - Evaluate multiple flags for multiple entities in a single request. More efficient than multiple single evaluation requests.
     - parameter evaluationBatchRequest: (body)  
     - returns: RequestBuilder<EvaluationBatchResponse> 
     */
    open class func postEvaluationBatchWithRequestBuilder(evaluationBatchRequest: EvaluationBatchRequest) -> RequestBuilder<EvaluationBatchResponse> {
        let localVariablePath = "/evaluation/batch"
        let localVariableURLString = FlagentClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: evaluationBatchRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EvaluationBatchResponse>.Type = FlagentClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
