//
// VariantAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(Combine)
import Combine
#endif
#if canImport(AnyCodable)
import AnyCodable
#endif

open class VariantAPI {

    /**
     Create variant
     
     - parameter flagId: (path) Numeric ID of the flag 
     - parameter createVariantRequest: (body)  
     - returns: AnyPublisher<Variant, Error>
     */
    #if canImport(Combine)
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createVariant(flagId: Int64, createVariantRequest: CreateVariantRequest) -> AnyPublisher<Variant, Error> {
        let requestBuilder = createVariantWithRequestBuilder(flagId: flagId, createVariantRequest: createVariantRequest)
        let requestTask = requestBuilder.requestTask
        return Future<Variant, Error> { promise in
            requestBuilder.execute { result in
                switch result {
                case let .success(response):
                    promise(.success(response.body))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }
        .handleEvents(receiveCancel: {
            requestTask.cancel()
        })
        .eraseToAnyPublisher()
    }
    #endif

    /**
     Create variant
     - POST /flags/{flagId}/variants
     - Create a variant for the flag. Variants are the possible outcomes of flag evaluation.
     - parameter flagId: (path) Numeric ID of the flag 
     - parameter createVariantRequest: (body)  
     - returns: RequestBuilder<Variant> 
     */
    open class func createVariantWithRequestBuilder(flagId: Int64, createVariantRequest: CreateVariantRequest) -> RequestBuilder<Variant> {
        var localVariablePath = "/flags/{flagId}/variants"
        let flagIdPreEscape = "\(APIHelper.mapValueToPathItem(flagId))"
        let flagIdPostEscape = flagIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{flagId}", with: flagIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = FlagentClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createVariantRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Variant>.Type = FlagentClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Delete variant
     
     - parameter flagId: (path) Numeric ID of the flag 
     - parameter variantId: (path) Numeric ID of the variant 
     - returns: AnyPublisher<Void, Error>
     */
    #if canImport(Combine)
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteVariant(flagId: Int64, variantId: Int64) -> AnyPublisher<Void, Error> {
        let requestBuilder = deleteVariantWithRequestBuilder(flagId: flagId, variantId: variantId)
        let requestTask = requestBuilder.requestTask
        return Future<Void, Error> { promise in
            requestBuilder.execute { result in
                switch result {
                case .success:
                    promise(.success(()))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }
        .handleEvents(receiveCancel: {
            requestTask.cancel()
        })
        .eraseToAnyPublisher()
    }
    #endif

    /**
     Delete variant
     - DELETE /flags/{flagId}/variants/{variantId}
     - Delete a variant. This will also remove it from all distributions.
     - parameter flagId: (path) Numeric ID of the flag 
     - parameter variantId: (path) Numeric ID of the variant 
     - returns: RequestBuilder<Void> 
     */
    open class func deleteVariantWithRequestBuilder(flagId: Int64, variantId: Int64) -> RequestBuilder<Void> {
        var localVariablePath = "/flags/{flagId}/variants/{variantId}"
        let flagIdPreEscape = "\(APIHelper.mapValueToPathItem(flagId))"
        let flagIdPostEscape = flagIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{flagId}", with: flagIdPostEscape, options: .literal, range: nil)
        let variantIdPreEscape = "\(APIHelper.mapValueToPathItem(variantId))"
        let variantIdPostEscape = variantIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{variantId}", with: variantIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = FlagentClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = FlagentClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get variants for flag
     
     - parameter flagId: (path) Numeric ID of the flag 
     - returns: AnyPublisher<[Variant], Error>
     */
    #if canImport(Combine)
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func findVariants(flagId: Int64) -> AnyPublisher<[Variant], Error> {
        let requestBuilder = findVariantsWithRequestBuilder(flagId: flagId)
        let requestTask = requestBuilder.requestTask
        return Future<[Variant], Error> { promise in
            requestBuilder.execute { result in
                switch result {
                case let .success(response):
                    promise(.success(response.body))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }
        .handleEvents(receiveCancel: {
            requestTask.cancel()
        })
        .eraseToAnyPublisher()
    }
    #endif

    /**
     Get variants for flag
     - GET /flags/{flagId}/variants
     - parameter flagId: (path) Numeric ID of the flag 
     - returns: RequestBuilder<[Variant]> 
     */
    open class func findVariantsWithRequestBuilder(flagId: Int64) -> RequestBuilder<[Variant]> {
        var localVariablePath = "/flags/{flagId}/variants"
        let flagIdPreEscape = "\(APIHelper.mapValueToPathItem(flagId))"
        let flagIdPostEscape = flagIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{flagId}", with: flagIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = FlagentClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Variant]>.Type = FlagentClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Update variant
     
     - parameter flagId: (path) Numeric ID of the flag 
     - parameter variantId: (path) Numeric ID of the variant 
     - parameter putVariantRequest: (body)  
     - returns: AnyPublisher<Variant, Error>
     */
    #if canImport(Combine)
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func putVariant(flagId: Int64, variantId: Int64, putVariantRequest: PutVariantRequest) -> AnyPublisher<Variant, Error> {
        let requestBuilder = putVariantWithRequestBuilder(flagId: flagId, variantId: variantId, putVariantRequest: putVariantRequest)
        let requestTask = requestBuilder.requestTask
        return Future<Variant, Error> { promise in
            requestBuilder.execute { result in
                switch result {
                case let .success(response):
                    promise(.success(response.body))
                case let .failure(error):
                    promise(.failure(error))
                }
            }
        }
        .handleEvents(receiveCancel: {
            requestTask.cancel()
        })
        .eraseToAnyPublisher()
    }
    #endif

    /**
     Update variant
     - PUT /flags/{flagId}/variants/{variantId}
     - parameter flagId: (path) Numeric ID of the flag 
     - parameter variantId: (path) Numeric ID of the variant 
     - parameter putVariantRequest: (body)  
     - returns: RequestBuilder<Variant> 
     */
    open class func putVariantWithRequestBuilder(flagId: Int64, variantId: Int64, putVariantRequest: PutVariantRequest) -> RequestBuilder<Variant> {
        var localVariablePath = "/flags/{flagId}/variants/{variantId}"
        let flagIdPreEscape = "\(APIHelper.mapValueToPathItem(flagId))"
        let flagIdPostEscape = flagIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{flagId}", with: flagIdPostEscape, options: .literal, range: nil)
        let variantIdPreEscape = "\(APIHelper.mapValueToPathItem(variantId))"
        let variantIdPostEscape = variantIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{variantId}", with: variantIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = FlagentClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: putVariantRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Variant>.Type = FlagentClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
