/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.flagent.client.models.CreateConstraintRequest

class CreateConstraintRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateConstraintRequest
        //val modelInstance = CreateConstraintRequest()

        // to test the property ``property``
        should("test `property`") {
            // uncomment below to test the property
            //modelInstance.`property` shouldBe ("TODO")
        }

        // to test the property ``operator``
        should("test `operator`") {
            // uncomment below to test the property
            //modelInstance.`operator` shouldBe ("TODO")
        }

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

    }
}
