/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.flagent.client.models.Variant

class VariantTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Variant
        //val modelInstance = Variant()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `flagID`
        should("test flagID") {
            // uncomment below to test the property
            //modelInstance.flagID shouldBe ("TODO")
        }

        // to test the property `key`
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

        // to test the property `attachment`
        should("test attachment") {
            // uncomment below to test the property
            //modelInstance.attachment shouldBe ("TODO")
        }

    }
}
