/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.apis

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

import com.flagent.client.apis.ConstraintApi
import com.flagent.client.models.Constraint
import com.flagent.client.models.CreateConstraintRequest
import com.flagent.client.models.Error
import com.flagent.client.models.PutConstraintRequest

class ConstraintApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConstraintApi
        //val apiInstance = ConstraintApi()

        // to test createConstraint
        should("test createConstraint") {
            // uncomment below to test createConstraint
            //val flagId : kotlin.Long = 789 // kotlin.Long | Numeric ID of the flag
            //val segmentId : kotlin.Long = 789 // kotlin.Long | Numeric ID of the segment
            //val createConstraintRequest : CreateConstraintRequest = {"property":"region","operator":"EQ","value":"US"} // CreateConstraintRequest | 
            //val result : Constraint = apiInstance.createConstraint(flagId, segmentId, createConstraintRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteConstraint
        should("test deleteConstraint") {
            // uncomment below to test deleteConstraint
            //val flagId : kotlin.Long = 789 // kotlin.Long | Numeric ID of the flag
            //val segmentId : kotlin.Long = 789 // kotlin.Long | Numeric ID of the segment
            //val constraintId : kotlin.Long = 789 // kotlin.Long | Numeric ID of the constraint
            //apiInstance.deleteConstraint(flagId, segmentId, constraintId)
        }

        // to test findConstraints
        should("test findConstraints") {
            // uncomment below to test findConstraints
            //val flagId : kotlin.Long = 789 // kotlin.Long | Numeric ID of the flag
            //val segmentId : kotlin.Long = 789 // kotlin.Long | Numeric ID of the segment
            //val result : kotlin.collections.List<Constraint> = apiInstance.findConstraints(flagId, segmentId)
            //result shouldBe ("TODO")
        }

        // to test putConstraint
        should("test putConstraint") {
            // uncomment below to test putConstraint
            //val flagId : kotlin.Long = 789 // kotlin.Long | Numeric ID of the flag
            //val segmentId : kotlin.Long = 789 // kotlin.Long | Numeric ID of the segment
            //val constraintId : kotlin.Long = 789 // kotlin.Long | Numeric ID of the constraint
            //val putConstraintRequest : PutConstraintRequest = {"property":"region","operator":"IN","value":"US,CA,MX"} // PutConstraintRequest | 
            //val result : Constraint = apiInstance.putConstraint(flagId, segmentId, constraintId, putConstraintRequest)
            //result shouldBe ("TODO")
        }

    }
}
