/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.apis

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec
import io.ktor.client.engine.mock.MockEngine
import io.ktor.client.engine.mock.respond
import io.ktor.http.HttpHeaders
import io.ktor.http.HttpStatusCode
import io.ktor.utils.io.ByteReadChannel
import kotlinx.coroutines.test.runTest
import com.flagent.client.models.PutDistributionsRequest
import com.flagent.client.models.DistributionRequest

class DistributionApiTest : ShouldSpec() {
    private val distributionJson = """{"id":1,"segmentID":10,"variantID":100,"percent":50,"variantKey":"control"}"""
    private val distributionListJson = """[$distributionJson]"""

    init {
        should("test findDistributions") {
            runTest {
                val mockEngine = MockEngine {
                    respond(ByteReadChannel(distributionListJson), HttpStatusCode.OK, io.ktor.http.headersOf(HttpHeaders.ContentType, "application/json"))
                }
                val api = DistributionApi(baseUrl = "http://localhost", httpClientEngine = mockEngine)
                val response = api.findDistributions(1L, 10L)
                response.status shouldBe 200
                val body = response.body()
                body.size shouldBe 1
                body[0].percent shouldBe 50L
            }
        }

        should("test putDistributions") {
            runTest {
                val mockEngine = MockEngine {
                    respond(ByteReadChannel(distributionListJson), HttpStatusCode.OK, io.ktor.http.headersOf(HttpHeaders.ContentType, "application/json"))
                }
                val api = DistributionApi(baseUrl = "http://localhost", httpClientEngine = mockEngine)
                val req = PutDistributionsRequest(distributions = listOf(DistributionRequest(variantID = 100L, percent = 50L, variantKey = "control")))
                val response = api.putDistributions(1L, 10L, req)
                response.status shouldBe 200
                response.body().size shouldBe 1
            }
        }
    }
}
