/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.flagent.client.apis.ExportApi
import com.flagent.client.models.Error

class ExportApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExportApi
        //val apiInstance = ExportApi()

        // to test getExportEvalCacheJSON
        should("test getExportEvalCacheJSON") {
            // uncomment below to test getExportEvalCacheJSON
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getExportEvalCacheJSON()
            //result shouldBe ("TODO")
        }

        // to test getExportSQLite
        should("test getExportSQLite") {
            // uncomment below to test getExportSQLite
            //val excludeSnapshots : kotlin.Boolean = true // kotlin.Boolean | Export without snapshots data - useful for smaller db without snapshots
            //val result : java.io.File = apiInstance.getExportSQLite(excludeSnapshots)
            //result shouldBe ("TODO")
        }

    }
}
