/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.flagent.client.apis.VariantApi
import com.flagent.client.models.CreateVariantRequest
import com.flagent.client.models.Error
import com.flagent.client.models.PutVariantRequest
import com.flagent.client.models.Variant

class VariantApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VariantApi
        //val apiInstance = VariantApi()

        // to test createVariant
        should("test createVariant") {
            // uncomment below to test createVariant
            //val flagId : kotlin.Long = 789 // kotlin.Long | Numeric ID of the flag
            //val createVariantRequest : CreateVariantRequest = {"key":"treatment","attachment":{"color":"blue","size":"large"}} // CreateVariantRequest | 
            //val result : Variant = apiInstance.createVariant(flagId, createVariantRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteVariant
        should("test deleteVariant") {
            // uncomment below to test deleteVariant
            //val flagId : kotlin.Long = 789 // kotlin.Long | Numeric ID of the flag
            //val variantId : kotlin.Long = 789 // kotlin.Long | Numeric ID of the variant
            //apiInstance.deleteVariant(flagId, variantId)
        }

        // to test findVariants
        should("test findVariants") {
            // uncomment below to test findVariants
            //val flagId : kotlin.Long = 789 // kotlin.Long | Numeric ID of the flag
            //val result : kotlin.collections.List<Variant> = apiInstance.findVariants(flagId)
            //result shouldBe ("TODO")
        }

        // to test putVariant
        should("test putVariant") {
            // uncomment below to test putVariant
            //val flagId : kotlin.Long = 789 // kotlin.Long | Numeric ID of the flag
            //val variantId : kotlin.Long = 789 // kotlin.Long | Numeric ID of the variant
            //val putVariantRequest : PutVariantRequest = {"key":"treatment_updated","attachment":{"color":"red","size":"small"}} // PutVariantRequest | 
            //val result : Variant = apiInstance.putVariant(flagId, variantId, putVariantRequest)
            //result shouldBe ("TODO")
        }

    }
}
