/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

class CreateConstraintRequestTest : ShouldSpec() {
    init {
        val modelInstance = CreateConstraintRequest(
            `property` = "tier",
            `operator` = "EQ",
            `value` = "premium"
        )

        should("test property") {
            modelInstance.`property` shouldBe "tier"
        }

        should("test operator") {
            modelInstance.`operator` shouldBe "EQ"
        }

        should("test value") {
            modelInstance.`value` shouldBe "premium"
        }
    }
}
