/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

class DistributionRequestTest : ShouldSpec() {
    init {
        val modelInstance = DistributionRequest(
            variantID = 100L,
            percent = 50L,
            variantKey = "control"
        )

        should("test variantID") {
            modelInstance.variantID shouldBe 100L
        }

        should("test percent") {
            modelInstance.percent shouldBe 50L
        }

        should("test variantKey") {
            modelInstance.variantKey shouldBe "control"
        }
    }
}
