/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec
import kotlin.time.Instant
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put

class EvalResultTest : ShouldSpec() {
    init {
        val evalContext = EvalContext(entityID = "user-1", entityType = "user")
        val evalDebugLog = EvalDebugLog(msg = "Debug info")
        val variantAttachment = buildJsonObject { put("payload", "value") }
        val timestamp = Instant.fromEpochMilliseconds(1704067200000L)
        val modelInstance = EvalResult(
            flagID = 1L,
            flagKey = "test_flag",
            flagSnapshotID = 100L,
            flagTags = listOf("tag1"),
            segmentID = 10L,
            variantID = 5L,
            variantKey = "control",
            variantAttachment = variantAttachment,
            evalContext = evalContext,
            timestamp = timestamp,
            evalDebugLog = evalDebugLog
        )

        should("test flagID") {
            modelInstance.flagID shouldBe 1L
        }

        should("test flagKey") {
            modelInstance.flagKey shouldBe "test_flag"
        }

        should("test flagSnapshotID") {
            modelInstance.flagSnapshotID shouldBe 100L
        }

        should("test flagTags") {
            modelInstance.flagTags shouldBe listOf("tag1")
        }

        should("test segmentID") {
            modelInstance.segmentID shouldBe 10L
        }

        should("test variantID") {
            modelInstance.variantID shouldBe 5L
        }

        should("test variantKey") {
            modelInstance.variantKey shouldBe "control"
        }

        should("test variantAttachment") {
            modelInstance.variantAttachment shouldBe variantAttachment
        }

        should("test evalContext") {
            modelInstance.evalContext shouldBe evalContext
        }

        should("test timestamp") {
            modelInstance.timestamp shouldBe timestamp
        }

        should("test evalDebugLog") {
            modelInstance.evalDebugLog shouldBe evalDebugLog
        }
    }
}
