/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

class EvaluationBatchResponseTest : ShouldSpec() {
    init {
        val evaluationResults = listOf(
            EvalResult(flagKey = "flag1", variantKey = "control"),
            EvalResult(flagKey = "flag2", variantKey = "treatment")
        )
        val modelInstance = EvaluationBatchResponse(evaluationResults = evaluationResults)

        should("test evaluationResults") {
            modelInstance.evaluationResults shouldBe evaluationResults
            modelInstance.evaluationResults.size shouldBe 2
            modelInstance.evaluationResults[0].flagKey shouldBe "flag1"
            modelInstance.evaluationResults[1].variantKey shouldBe "treatment"
        }
    }
}
