/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

class FlagTest : ShouldSpec() {
    init {
        val segments = listOf(
            Segment(1L, 10L, "Segment 1", 0L, 100L, null, null)
        )
        val variants = listOf(
            Variant(1L, 10L, "control", null),
            Variant(2L, 10L, "treatment", null)
        )
        val tags = listOf(Tag(1L, "feature"))
        val modelInstance = Flag(
            id = 1L,
            key = "test_flag",
            description = "Test feature flag",
            enabled = true,
            dataRecordsEnabled = false,
            snapshotID = 100L,
            entityType = "user",
            notes = "# Notes",
            createdBy = "admin",
            updatedBy = "admin",
            segments = segments,
            variants = variants,
            tags = tags
        )

        should("test id") {
            modelInstance.id shouldBe 1L
        }

        should("test key") {
            modelInstance.key shouldBe "test_flag"
        }

        should("test description") {
            modelInstance.description shouldBe "Test feature flag"
        }

        should("test enabled") {
            modelInstance.enabled shouldBe true
        }

        should("test dataRecordsEnabled") {
            modelInstance.dataRecordsEnabled shouldBe false
        }

        should("test snapshotID") {
            modelInstance.snapshotID shouldBe 100L
        }

        should("test entityType") {
            modelInstance.entityType shouldBe "user"
        }

        should("test notes") {
            modelInstance.notes shouldBe "# Notes"
        }

        should("test createdBy") {
            modelInstance.createdBy shouldBe "admin"
        }

        should("test updatedBy") {
            modelInstance.updatedBy shouldBe "admin"
        }

        should("test segments") {
            modelInstance.segments shouldBe segments
        }

        should("test variants") {
            modelInstance.variants shouldBe variants
        }

        should("test tags") {
            modelInstance.tags shouldBe tags
        }
    }
}
