/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

class PutFlagRequestTest : ShouldSpec() {
    init {
        val modelInstance = PutFlagRequest(
            description = "Updated description",
            key = "updated_key",
            dataRecordsEnabled = true,
            entityType = "user",
            notes = "# Usage notes"
        )

        should("test description") {
            modelInstance.description shouldBe "Updated description"
        }

        should("test key") {
            modelInstance.key shouldBe "updated_key"
        }

        should("test dataRecordsEnabled") {
            modelInstance.dataRecordsEnabled shouldBe true
        }

        should("test entityType") {
            modelInstance.entityType shouldBe "user"
        }

        should("test notes") {
            modelInstance.notes shouldBe "# Usage notes"
        }
    }
}
