/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import io.kotest.matchers.shouldBe
import io.kotest.core.spec.style.ShouldSpec

class SegmentDebugLogTest : ShouldSpec() {
    init {
        val modelInstance = SegmentDebugLog(
            segmentID = 10L,
            msg = "Segment matched"
        )

        should("test segmentID") {
            modelInstance.segmentID shouldBe 10L
        }

        should("test msg") {
            modelInstance.msg shouldBe "Segment matched"
        }
    }
}
