//
// EvaluationBatchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EvaluationBatchRequest: Codable, JSONEncodable, Hashable {

    public enum FlagTagsOperator: String, Codable, CaseIterable {
        case any = "ANY"
        case all = "ALL"
    }
    public static let entitiesRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public var entities: [EvaluationEntity]
    public var enableDebug: Bool? = false
    /** FlagIDs. Either flagIDs, flagKeys or flagTags works. If pass in multiples, Flagent may return duplicate results. */
    public var flagIDs: [Int]?
    /** FlagKeys. Either flagIDs, flagKeys or flagTags works. If pass in multiples, Flagent may return duplicate results. */
    public var flagKeys: [String]?
    /** FlagTags. Either flagIDs, flagKeys or flagTags works. If pass in multiples, Flagent may return duplicate results. */
    public var flagTags: [String]?
    /** Determine how flagTags is used to filter flags to be evaluated. */
    public var flagTagsOperator: FlagTagsOperator? = .any

    public init(entities: [EvaluationEntity], enableDebug: Bool? = false, flagIDs: [Int]? = nil, flagKeys: [String]? = nil, flagTags: [String]? = nil, flagTagsOperator: FlagTagsOperator? = .any) {
        self.entities = entities
        self.enableDebug = enableDebug
        self.flagIDs = flagIDs
        self.flagKeys = flagKeys
        self.flagTags = flagTags
        self.flagTagsOperator = flagTagsOperator
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entities
        case enableDebug
        case flagIDs
        case flagKeys
        case flagTags
        case flagTagsOperator
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(entities, forKey: .entities)
        try container.encodeIfPresent(enableDebug, forKey: .enableDebug)
        try container.encodeIfPresent(flagIDs, forKey: .flagIDs)
        try container.encodeIfPresent(flagKeys, forKey: .flagKeys)
        try container.encodeIfPresent(flagTags, forKey: .flagTags)
        try container.encodeIfPresent(flagTagsOperator, forKey: .flagTagsOperator)
    }
}

