//
// Flag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Flag: Codable, JSONEncodable, Hashable {

    public static let idRule = NumericRule<Int64>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int64
    /** Unique key representation of the flag */
    public var key: String
    public var description: String
    public var enabled: Bool
    public var snapshotID: Int64?
    /** Enabled data records will get data logging in the metrics pipeline */
    public var dataRecordsEnabled: Bool
    /** It will override the entityType in the evaluation logs if it's not empty */
    public var entityType: String?
    /** Flag usage details in markdown format */
    public var notes: String?
    public var createdBy: String?
    public var updatedBy: String?
    public var segments: [Segment]?
    public var variants: [Variant]?
    public var tags: [Tag]?

    public init(id: Int64, key: String, description: String, enabled: Bool, snapshotID: Int64? = nil, dataRecordsEnabled: Bool, entityType: String? = nil, notes: String? = nil, createdBy: String? = nil, updatedBy: String? = nil, segments: [Segment]? = nil, variants: [Variant]? = nil, tags: [Tag]? = nil) {
        self.id = id
        self.key = key
        self.description = description
        self.enabled = enabled
        self.snapshotID = snapshotID
        self.dataRecordsEnabled = dataRecordsEnabled
        self.entityType = entityType
        self.notes = notes
        self.createdBy = createdBy
        self.updatedBy = updatedBy
        self.segments = segments
        self.variants = variants
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case key
        case description
        case enabled
        case snapshotID
        case dataRecordsEnabled
        case entityType
        case notes
        case createdBy
        case updatedBy
        case segments
        case variants
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(key, forKey: .key)
        try container.encode(description, forKey: .description)
        try container.encode(enabled, forKey: .enabled)
        try container.encodeIfPresent(snapshotID, forKey: .snapshotID)
        try container.encode(dataRecordsEnabled, forKey: .dataRecordsEnabled)
        try container.encodeIfPresent(entityType, forKey: .entityType)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(createdBy, forKey: .createdBy)
        try container.encodeIfPresent(updatedBy, forKey: .updatedBy)
        try container.encodeIfPresent(segments, forKey: .segments)
        try container.encodeIfPresent(variants, forKey: .variants)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Flag: Identifiable {}
