//
// FlagSnapshot.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FlagSnapshot: Codable, JSONEncodable, Hashable {

    public static let idRule = NumericRule<Int64>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int64
    public var updatedBy: String?
    public var flag: Flag
    public var updatedAt: Date

    public init(id: Int64, updatedBy: String? = nil, flag: Flag, updatedAt: Date) {
        self.id = id
        self.updatedBy = updatedBy
        self.flag = flag
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case updatedBy
        case flag
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(updatedBy, forKey: .updatedBy)
        try container.encode(flag, forKey: .flag)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension FlagSnapshot: Identifiable {}
