//
// PutDistributionsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PutDistributionsRequest: Codable, JSONEncodable, Hashable {

    public var distributions: [DistributionRequest]

    public init(distributions: [DistributionRequest]) {
        self.distributions = distributions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case distributions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(distributions, forKey: .distributions)
    }
}

