//
// Segment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Segment: Codable, JSONEncodable, Hashable {

    public static let idRule = NumericRule<Int64>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let rankRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let rolloutPercentRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int64
    public var flagID: Int64
    public var description: String
    public var rank: Int64
    public var rolloutPercent: Int64
    public var constraints: [Constraint]?
    public var distributions: [Distribution]?

    public init(id: Int64, flagID: Int64, description: String, rank: Int64, rolloutPercent: Int64, constraints: [Constraint]? = nil, distributions: [Distribution]? = nil) {
        self.id = id
        self.flagID = flagID
        self.description = description
        self.rank = rank
        self.rolloutPercent = rolloutPercent
        self.constraints = constraints
        self.distributions = distributions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case flagID
        case description
        case rank
        case rolloutPercent
        case constraints
        case distributions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(flagID, forKey: .flagID)
        try container.encode(description, forKey: .description)
        try container.encode(rank, forKey: .rank)
        try container.encode(rolloutPercent, forKey: .rolloutPercent)
        try container.encodeIfPresent(constraints, forKey: .constraints)
        try container.encodeIfPresent(distributions, forKey: .distributions)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Segment: Identifiable {}
