/* tslint:disable */
/* eslint-disable */
/**
 * Flagent API
 * Flagent is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". ## Authentication Flagent supports multiple authentication methods (configured via environment variables): - **JWT Authentication**: Bearer token authentication - **Basic Authentication**: Username/password authentication - **Header Authentication**: Custom header-based authentication - **Cookie Authentication**: Cookie-based authentication Some endpoints (like `/health`, `/evaluation`) may be whitelisted and don\'t require authentication. ## Error Responses All error responses follow the same format: ```json {   \"message\": \"Error description\" } ``` Common HTTP status codes: - `200`: Success - `400`: Bad Request - invalid input parameters - `404`: Not Found - resource doesn\'t exist - `429`: Too Many Requests - rate limit exceeded - `500`: Internal Server Error - server error ## Rate Limiting Rate limiting is configured via environment variables: - `FLAGENT_RATELIMITER_PERFLAG_PERSECOND_CONSOLE_LOGGING`: Maximum evaluations per flag per second (default: 100) When rate limit is exceeded, the API returns `429 Too Many Requests` status code. ## Best Practices - Use batch evaluation (`/evaluation/batch`) when evaluating multiple flags for multiple entities - Use `enableDebug: true` only in development environments - Preload flags with `preload=true` parameter when fetching flags to reduce subsequent API calls - Use tags to organize and filter flags efficiently 
 *
 * The version of the OpenAPI document: 1.1.19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * ExportApi - axios parameter creator
 */
export const ExportApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Export JSON format of the eval cache dump. This endpoint exports the current state of the evaluation cache in JSON format.
         * @summary Export eval cache as JSON
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExportEvalCacheJSON: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/export/eval_cache/json`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Export sqlite3 format of the db dump, which is converted from the main database. Returns a SQLite database file that can be used for backup or migration purposes.
         * @summary Export database as SQLite
         * @param {boolean} [excludeSnapshots] Export without snapshots data - useful for smaller db without snapshots
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExportSQLite: async (excludeSnapshots?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/export/sqlite`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (excludeSnapshots !== undefined) {
                localVarQueryParameter['exclude_snapshots'] = excludeSnapshots;
            }

            localVarHeaderParameter['Accept'] = 'application/octet-stream,application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExportApi - functional programming interface
 */
export const ExportApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExportApiAxiosParamCreator(configuration)
    return {
        /**
         * Export JSON format of the eval cache dump. This endpoint exports the current state of the evaluation cache in JSON format.
         * @summary Export eval cache as JSON
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExportEvalCacheJSON(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExportEvalCacheJSON(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExportApi.getExportEvalCacheJSON']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Export sqlite3 format of the db dump, which is converted from the main database. Returns a SQLite database file that can be used for backup or migration purposes.
         * @summary Export database as SQLite
         * @param {boolean} [excludeSnapshots] Export without snapshots data - useful for smaller db without snapshots
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getExportSQLite(excludeSnapshots?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getExportSQLite(excludeSnapshots, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExportApi.getExportSQLite']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExportApi - factory interface
 */
export const ExportApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExportApiFp(configuration)
    return {
        /**
         * Export JSON format of the eval cache dump. This endpoint exports the current state of the evaluation cache in JSON format.
         * @summary Export eval cache as JSON
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExportEvalCacheJSON(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.getExportEvalCacheJSON(options).then((request) => request(axios, basePath));
        },
        /**
         * Export sqlite3 format of the db dump, which is converted from the main database. Returns a SQLite database file that can be used for backup or migration purposes.
         * @summary Export database as SQLite
         * @param {boolean} [excludeSnapshots] Export without snapshots data - useful for smaller db without snapshots
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getExportSQLite(excludeSnapshots?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.getExportSQLite(excludeSnapshots, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ExportApi - interface
 */
export interface ExportApiInterface {
    /**
     * Export JSON format of the eval cache dump. This endpoint exports the current state of the evaluation cache in JSON format.
     * @summary Export eval cache as JSON
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getExportEvalCacheJSON(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }>;

    /**
     * Export sqlite3 format of the db dump, which is converted from the main database. Returns a SQLite database file that can be used for backup or migration purposes.
     * @summary Export database as SQLite
     * @param {boolean} [excludeSnapshots] Export without snapshots data - useful for smaller db without snapshots
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getExportSQLite(excludeSnapshots?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<File>;

}

/**
 * ExportApi - object-oriented interface
 */
export class ExportApi extends BaseAPI implements ExportApiInterface {
    /**
     * Export JSON format of the eval cache dump. This endpoint exports the current state of the evaluation cache in JSON format.
     * @summary Export eval cache as JSON
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getExportEvalCacheJSON(options?: RawAxiosRequestConfig) {
        return ExportApiFp(this.configuration).getExportEvalCacheJSON(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Export sqlite3 format of the db dump, which is converted from the main database. Returns a SQLite database file that can be used for backup or migration purposes.
     * @summary Export database as SQLite
     * @param {boolean} [excludeSnapshots] Export without snapshots data - useful for smaller db without snapshots
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getExportSQLite(excludeSnapshots?: boolean, options?: RawAxiosRequestConfig) {
        return ExportApiFp(this.configuration).getExportSQLite(excludeSnapshots, options).then((request) => request(this.axios, this.basePath));
    }
}

