/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import kotlinx.serialization.json.JsonObject


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param entityID 
 * @param entityType 
 * @param entityContext 
 */
@Serializable

data class EvaluationEntity (

    @SerialName(value = "entityID") val entityID: kotlin.String? = null,

    @SerialName(value = "entityType") val entityType: kotlin.String? = null,

    @SerialName(value = "entityContext") val entityContext: kotlinx.serialization.json.JsonObject? = null

) {


}

