/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param segmentIDs 
 */
@Serializable

data class PutSegmentReorderRequest (

    @SerialName(value = "segmentIDs") @Required val segmentIDs: kotlin.collections.List<kotlin.Long>

) {


}

