/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.flagent.client.models

import com.flagent.client.models.Constraint
import com.flagent.client.models.Distribution

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param flagID 
 * @param description 
 * @param rank 
 * @param rolloutPercent 
 * @param constraints 
 * @param distributions 
 */
@Serializable

data class Segment (

    @SerialName(value = "id") @Required val id: kotlin.Long,

    @SerialName(value = "flagID") @Required val flagID: kotlin.Long,

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "rank") @Required val rank: kotlin.Long,

    @SerialName(value = "rolloutPercent") @Required val rolloutPercent: kotlin.Long,

    @SerialName(value = "constraints") val constraints: kotlin.collections.List<Constraint>? = null,

    @SerialName(value = "distributions") val distributions: kotlin.collections.List<Distribution>? = null

) {


}

